# Ajustes - Outubro 2023

## Condutores
- Determinar quantidade de novos condutores por ano
- Testar modelo com população novamente

```{r}
source(here("R/main.R"))
conflicted::conflicts_prefer(dplyr::lag)
```

```{r}
novos_condutores <- prediction |> 
  mutate(novos_condutores = condutores - lag(condutores)) |> 
  select(novos_condutores, condutores, everything())

novos_condutores

novos_condutores |> 
  ggplot(aes(x = ano, y = novos_condutores)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(limits = c(2012,2021), breaks = seq(2012,2021,1))
```

Queda brusca de novos condutores em 2020, provavelmente devido à pandemia

## Taxas de mortes

```{r}
taxas <- novos_condutores |> 
  mutate(
    mortes_100mil_hab = (mortes/populacao)*100000,
    mortes_10mil_veic = (mortes/veiculos_total)*10000
  ) |> 
  select(mortes_100mil_hab, mortes_10mil_veic, everything())

taxas

taxas |> 
  ggplot(aes(x = ano, y = mortes_100mil_hab)) + 
  geom_line() +
  scale_x_continuous(limits = c(1996,2021), breaks = seq(1996,2021,1)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

taxas |> 
  ggplot(aes(x = ano, y = mortes_10mil_veic)) +
  geom_line() +
  scale_x_continuous(limits = c(1999,2021), breaks = seq(1996,2021,1)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
taxas_pred <- taxas |> 
  mutate(
    mortes_100mil_hab_pred = (mortes.pred/populacao)*100000,
    mortes_10mil_veic_pred = (mortes.pred/veiculos_total)*10000
  ) |> 
  select(mortes_100mil_hab_pred, mortes_10mil_veic_pred, everything())

taxas_pred

taxas_pred |> 
  select(ano, mortes_100mil_hab_pred, mortes_100mil_hab) |> 
  pivot_longer(cols = c(mortes_100mil_hab_pred, mortes_100mil_hab)) |> 
  ggplot(aes(x = ano, y = value, color = name)) +
  geom_line() + geom_point() +
  scale_x_continuous(limits = c(1996,2021), breaks = seq(1996,2021,1)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

taxas_pred |> 
  select(ano, mortes_10mil_veic_pred, mortes_10mil_veic) |> 
  pivot_longer(cols = c(mortes_10mil_veic_pred, mortes_10mil_veic)) |> 
  ggplot(aes(x = ano, y = value, color = name)) +
  geom_line() + geom_point() +
  scale_x_continuous(limits = c(1996,2021), breaks = seq(1996,2021,1)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## Avaliando novamente população como variável

```{r}
# limpa o global environment
rm(list = ls())

load(here("data/tabela_total.rda"))

source(here("R/linear_model.R"))

res <- df_total |> 
  lm_model() |> 
  lm_extract(df_total)

prediction <- res$pred

dados2022 <- list(
  "ano" = 2022,
  "qnt_acidentes" = 64547,
  "qnt_acidentes_fatais" = 4662,
  "condutores" = 79921178,
  "veiculos_total" = 115116532,
  "populacao" = 203062512
) |> as.data.frame()

df_2022 <- bind_rows(drop_na(df_total), dados2022)

res2 <- df_total |>
  lm_model() |>
  lm_extract(df_2022)

prediction2 <- res2$pred
```

```{r}
res2$erros
```

```{r}

```

